language: java
jdk: oraclejdk8
script:
  - mvn clean install sonar:sonar -Dsonar.projectKey=chrisesharp_pacman-redux
addons:
  sonarcloud:
    organization: "chrisesharp-github"
    token:
      secure: "LcK8ajS47W31vnFf0GdSuW6xQLUAl+0vSFv8mz/NNiVaBxzM710h6ebiU4h6BroZdTttSuCuEbQTBb7pcZIHRcnwbg4yd2RYQ2mtNvlpYt1sFZbbrcLMCHoCc4ShJEmvlYtKfMQRuAa7BU8sFppwginZyVFaPTp1tI3tkVCOmmA7tqsmor+DJ5sDrvjWsas+oPTTEj05pY3Ob+43XN9mfPXGqKC8U8+giPKvjTHX22kRyiGaIimSA/mq+RyJtWFnuR6mR34o3nbe5Wb4qoTthEiD7JlxLM5gReVVrV/+ehT5LI6KEBMbfS8PPpPEpvWUcgT4M2d+fXNbq6BAujw8Rhc8iP40VuO9zQXNYNVHtX7quY8S9+YYV5VsMqBuiWUou2ZUX14YkbFleCKfoc1TnvWOEXNn+aHlIs/t1i80deEa6S60G/FMMWY/Weoddb7bTe6W4qOMNLxoKXvl9FMX53wudvrKoB1i72LXrSiGgvs52KUJOxj71DRRX6UAVnYwOT7r419dJNCStA3CWTeeZ2yfQpLdRlZgdQnvAVQSS0ya8eZjjVSRIp0BFtTclZJFPTzgflq5lM/8lztBhpjPnw3LSvh4S6ynLTEv8DWu5zeh2GDhpkHG93MF623kyQXsxHHdBVnBI4gEXQPovq3uKfHDOXcwGCrl1hjdpxBkAE0="