language: java
jdk: oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install  sonar:sonar -Dsonar.projectKey=chrisesharp_pac-start
addons:
  sonarcloud:
    organization: "chrisesharp-github"
    token:
      secure: "bi4tTU+q5ZcxCB4oUYfzRl3xC/chLasdVc3ITVR+9AUoNPZD94Uf6WP7DWFJ/szLfMFOsgreFE2odk616Jd0Lt92b3TJ+TcAvyVUCIsGIwp2yo1dXMHYRCbMrjyvmQZATR975m60040njikjDI9+IVvOhBmpoC7msyZot/uvoNY2vpzokmiMj1qE/j1bxnVNSOjWoW1CnjST8axWQK/7Pj3o7mQKYoF2Vsdr5EvlXyZVmPGIz1zWLvdmdx5kc99neNSwKVeEk1sMfkF7VwPUFrHN2lNu09d/2/oQJBMUwYI0lf26GO6R5Jduej1Ut1yJSCtKvGFhwajX3GG6HcrRnamawmRl3h8Sm1EW1ji+8bgFY8ZdcSSXMbF2NpnXqldrlF3bbJrbdeCZ+BdqDeBWw31BwGjqOI5NEmzvJN5UMU688v2IcVTr1qOlGW4+7CbgPASVeq4MqlCjGSgKcpSKnSgD7QvNp3Qj5mOEfzCx1P/IuLQH+3yZ4YNnJxmY1RclMaxJ8ZF0nzvvJ33gmkMnNpno4dgOrgwd+0hS8uniRuGnwoIRzwoN/ucKa21Jb0F3qJpg+4/JdIWmgG0LVYTKjcLz4c4/JNW2jPZ+Ts6hTTnEHXrST72yOXaR56mBxPZXh3rPyfPZuixnrF8CyAnigzSw0UbBBqC1vHsa11Fk2s4="